-- EVE Football Scanner
-- ONE-SHOT setup for the DEDICATED FREE Supabase project only.
-- Project: eve-football-scanner (MCSETUPS)
-- This file combines migrations 001, 002 and 003.

create extension if not exists pgcrypto;

create table if not exists public.countries (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.leagues (
  id uuid primary key default gen_random_uuid(),
  country_id uuid not null references public.countries(id) on delete cascade,
  name text not null,
  slug text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  source_key text unique,
  name text not null,
  short_name text,
  country_id uuid references public.countries(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.referees (
  id uuid primary key default gen_random_uuid(),
  source_key text unique,
  name text not null,
  country_id uuid references public.countries(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.fixtures (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  source_fixture_id text not null,
  league_id uuid not null references public.leagues(id) on delete cascade,
  home_team_id uuid not null references public.teams(id) on delete restrict,
  away_team_id uuid not null references public.teams(id) on delete restrict,
  referee_id uuid references public.referees(id) on delete set null,
  kickoff timestamptz not null,
  status text not null default 'scheduled' check (status in ('scheduled','live','finished','postponed','cancelled')),
  home_goals smallint,
  away_goals smallint,
  weather jsonb not null default '{}'::jsonb,
  match_context jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(source, source_fixture_id),
  check (home_team_id <> away_team_id)
);

create table if not exists public.team_match_stats (
  id bigint generated by default as identity primary key,
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  venue text not null check (venue in ('home','away')),
  goals smallint,
  yellow_cards smallint,
  red_cards smallint,
  corners smallint,
  fouls smallint,
  shots smallint,
  shots_on_target smallint,
  xg numeric(6,3),
  possession numeric(5,2),
  source text not null,
  source_payload_hash text,
  created_at timestamptz not null default now(),
  unique(fixture_id, team_id)
);

create table if not exists public.referee_profiles (
  id bigint generated by default as identity primary key,
  referee_id uuid not null references public.referees(id) on delete cascade,
  as_of_date date not null,
  matches_sample smallint not null default 0,
  yellow_cards_per_match numeric(5,2),
  red_cards_per_match numeric(5,3),
  fouls_per_match numeric(5,2),
  penalties_per_match numeric(5,3),
  home_yellows_per_match numeric(5,2),
  away_yellows_per_match numeric(5,2),
  source text not null,
  created_at timestamptz not null default now(),
  unique(referee_id, as_of_date, source)
);

create table if not exists public.feature_snapshots (
  id uuid primary key default gen_random_uuid(),
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  market text not null check (market in ('cards','corners','goals')),
  selection_key text not null,
  selection_label text not null,
  data_quality smallint not null check (data_quality between 0 and 100),
  features jsonb not null,
  evidence jsonb not null default '[]'::jsonb,
  model_version text not null default 'v0-research',
  calculated_at timestamptz not null default now(),
  unique(fixture_id, selection_key, model_version)
);

create table if not exists public.predictions (
  id uuid primary key default gen_random_uuid(),
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  feature_snapshot_id uuid references public.feature_snapshots(id) on delete set null,
  market text not null check (market in ('cards','corners','goals')),
  selection text not null,
  confidence smallint not null check (confidence between 0 and 100),
  grade text not null check (grade in ('A+','A','B','C')),
  data_quality smallint not null check (data_quality between 0 and 100),
  evidence jsonb not null default '[]'::jsonb,
  fair_probability numeric(6,5),
  model_version text not null default 'v0-research',
  publish_status text not null default 'draft' check (publish_status in ('draft','published','suppressed')),
  generated_at timestamptz not null default now(),
  unique(fixture_id, selection, model_version)
);

create table if not exists public.odds_snapshots (
  id bigint generated by default as identity primary key,
  prediction_id uuid not null references public.predictions(id) on delete cascade,
  bookmaker text not null,
  decimal_odds numeric(8,3) not null check (decimal_odds > 1),
  captured_at timestamptz not null default now(),
  is_closing boolean not null default false
);

create table if not exists public.prediction_results (
  prediction_id uuid primary key references public.predictions(id) on delete cascade,
  outcome text not null check (outcome in ('win','loss','void','push')),
  settled_at timestamptz not null default now(),
  taken_odds numeric(8,3),
  closing_odds numeric(8,3),
  profit_units numeric(10,4),
  notes text
);

create table if not exists public.source_sync_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  job_name text not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running' check (status in ('running','success','partial','failed')),
  rows_upserted integer not null default 0,
  error_message text
);

create index if not exists fixtures_kickoff_idx on public.fixtures(kickoff);
create index if not exists fixtures_league_kickoff_idx on public.fixtures(league_id, kickoff);
create index if not exists team_match_stats_team_fixture_idx on public.team_match_stats(team_id, fixture_id);
create index if not exists referee_profiles_ref_date_idx on public.referee_profiles(referee_id, as_of_date desc);
create index if not exists predictions_fixture_market_idx on public.predictions(fixture_id, market);
create index if not exists predictions_publish_confidence_idx on public.predictions(publish_status, confidence desc);
create index if not exists odds_prediction_time_idx on public.odds_snapshots(prediction_id, captured_at desc);

alter table public.fixtures
  add column if not exists half_time_home_goals smallint,
  add column if not exists half_time_away_goals smallint;

create or replace view public.team_match_flat
with (security_invoker = true)
as
select
  f.id as fixture_id,
  f.kickoff,
  f.league_id,
  f.referee_id,
  f.status,
  hs.team_id,
  f.away_team_id as opponent_team_id,
  'home'::text as venue,
  hs.goals,
  hs.yellow_cards,
  hs.red_cards,
  hs.corners,
  hs.fouls,
  hs.shots,
  hs.shots_on_target,
  hs.xg,
  aw.yellow_cards as opponent_yellow_cards,
  aw.corners as opponent_corners,
  aw.goals as opponent_goals,
  f.home_goals,
  f.away_goals,
  f.half_time_home_goals,
  f.half_time_away_goals
from public.fixtures f
join public.team_match_stats hs on hs.fixture_id = f.id and hs.team_id = f.home_team_id
join public.team_match_stats aw on aw.fixture_id = f.id and aw.team_id = f.away_team_id
where f.status = 'finished'
union all
select
  f.id as fixture_id,
  f.kickoff,
  f.league_id,
  f.referee_id,
  f.status,
  aw.team_id,
  f.home_team_id as opponent_team_id,
  'away'::text as venue,
  aw.goals,
  aw.yellow_cards,
  aw.red_cards,
  aw.corners,
  aw.fouls,
  aw.shots,
  aw.shots_on_target,
  aw.xg,
  hs.yellow_cards as opponent_yellow_cards,
  hs.corners as opponent_corners,
  hs.goals as opponent_goals,
  f.home_goals,
  f.away_goals,
  f.half_time_home_goals,
  f.half_time_away_goals
from public.fixtures f
join public.team_match_stats hs on hs.fixture_id = f.id and hs.team_id = f.home_team_id
join public.team_match_stats aw on aw.fixture_id = f.id and aw.team_id = f.away_team_id
where f.status = 'finished';

create or replace function public.refresh_referee_profiles()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer := 0;
begin
  insert into public.referee_profiles (
    referee_id,
    as_of_date,
    matches_sample,
    yellow_cards_per_match,
    red_cards_per_match,
    fouls_per_match,
    home_yellows_per_match,
    away_yellows_per_match,
    source
  )
  select
    f.referee_id,
    current_date,
    count(*)::smallint,
    round(avg(coalesce(hs.yellow_cards,0) + coalesce(aw.yellow_cards,0))::numeric, 2),
    round(avg(coalesce(hs.red_cards,0) + coalesce(aw.red_cards,0))::numeric, 3),
    round(avg(coalesce(hs.fouls,0) + coalesce(aw.fouls,0))::numeric, 2),
    round(avg(coalesce(hs.yellow_cards,0))::numeric, 2),
    round(avg(coalesce(aw.yellow_cards,0))::numeric, 2),
    'eve-derived'
  from public.fixtures f
  join public.team_match_stats hs on hs.fixture_id = f.id and hs.team_id = f.home_team_id
  join public.team_match_stats aw on aw.fixture_id = f.id and aw.team_id = f.away_team_id
  where f.status = 'finished'
    and f.referee_id is not null
    and f.kickoff >= now() - interval '730 days'
  group by f.referee_id
  having count(*) >= 3
  on conflict (referee_id, as_of_date, source)
  do update set
    matches_sample = excluded.matches_sample,
    yellow_cards_per_match = excluded.yellow_cards_per_match,
    red_cards_per_match = excluded.red_cards_per_match,
    fouls_per_match = excluded.fouls_per_match,
    home_yellows_per_match = excluded.home_yellows_per_match,
    away_yellows_per_match = excluded.away_yellows_per_match,
    created_at = now();

  get diagnostics affected = row_count;
  return affected;
end;
$$;

create or replace function public.settle_v0_predictions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  affected integer := 0;
begin
  insert into public.prediction_results (prediction_id, outcome, settled_at)
  select
    p.id,
    case
      when fs.selection_key = 'home_cards_1_5' then case when coalesce(hs.yellow_cards, -1) >= 2 then 'win' else 'loss' end
      when fs.selection_key = 'away_cards_1_5' then case when coalesce(aw.yellow_cards, -1) >= 2 then 'win' else 'loss' end
      when fs.selection_key = 'home_corners_4_5' then case when coalesce(hs.corners, -1) >= 5 then 'win' else 'loss' end
      when fs.selection_key = 'away_corners_4_5' then case when coalesce(aw.corners, -1) >= 5 then 'win' else 'loss' end
      when fs.selection_key = 'over_1_5' then case when coalesce(f.home_goals, 0) + coalesce(f.away_goals, 0) >= 2 then 'win' else 'loss' end
      when fs.selection_key = 'second_half_0_5' then case
        when (coalesce(f.home_goals, 0) + coalesce(f.away_goals, 0))
           - (coalesce(f.half_time_home_goals, 0) + coalesce(f.half_time_away_goals, 0)) >= 1 then 'win'
        else 'loss'
      end
      else 'void'
    end,
    now()
  from public.predictions p
  join public.feature_snapshots fs on fs.id = p.feature_snapshot_id
  join public.fixtures f on f.id = p.fixture_id and f.status = 'finished'
  left join public.team_match_stats hs on hs.fixture_id = f.id and hs.team_id = f.home_team_id
  left join public.team_match_stats aw on aw.fixture_id = f.id and aw.team_id = f.away_team_id
  left join public.prediction_results existing on existing.prediction_id = p.id
  where existing.prediction_id is null
    and p.model_version = 'v0-research';

  get diagnostics affected = row_count;
  return affected;
end;
$$;

create or replace view public.scanner_best_bets
with (security_invoker = true)
as
select
  p.id,
  c.name as country,
  l.name as league,
  ht.name as "homeTeam",
  at.name as "awayTeam",
  to_char(f.kickoff at time zone 'Europe/London', 'HH24:MI') as kickoff,
  p.market,
  p.selection,
  p.confidence,
  p.grade,
  p.data_quality as "dataQuality",
  p.evidence,
  case when r.id is null then null else jsonb_build_object(
    'name', r.name,
    'cardsPerMatch', rp.yellow_cards_per_match,
    'foulsPerMatch', rp.fouls_per_match
  ) end as referee,
  null::text as "researchNote"
from public.predictions p
join public.fixtures f on f.id = p.fixture_id
join public.leagues l on l.id = f.league_id
join public.countries c on c.id = l.country_id
join public.teams ht on ht.id = f.home_team_id
join public.teams at on at.id = f.away_team_id
left join public.referees r on r.id = f.referee_id
left join lateral (
  select yellow_cards_per_match, fouls_per_match
  from public.referee_profiles rp0
  where rp0.referee_id = r.id
  order by rp0.as_of_date desc
  limit 1
) rp on true
where p.publish_status = 'published'
  and f.status in ('scheduled','live')
  and f.kickoff >= now() - interval '3 hours'
order by p.confidence desc;

create or replace view public.scanner_performance
with (security_invoker = true)
as
select
  p.market,
  p.grade,
  p.model_version,
  count(*) filter (where r.outcome in ('win','loss'))::integer as settled,
  count(*) filter (where r.outcome = 'win')::integer as wins,
  count(*) filter (where r.outcome = 'loss')::integer as losses,
  case
    when count(*) filter (where r.outcome in ('win','loss')) = 0 then null
    else round(
      100.0 * count(*) filter (where r.outcome = 'win')
      / count(*) filter (where r.outcome in ('win','loss')),
      1
    )
  end as hit_rate
from public.predictions p
join public.prediction_results r on r.prediction_id = p.id
where p.publish_status = 'published'
group by p.market, p.grade, p.model_version
order by p.market, p.grade;

alter table public.countries enable row level security;
alter table public.leagues enable row level security;
alter table public.teams enable row level security;
alter table public.referees enable row level security;
alter table public.fixtures enable row level security;
alter table public.team_match_stats enable row level security;
alter table public.referee_profiles enable row level security;
alter table public.feature_snapshots enable row level security;
alter table public.predictions enable row level security;
alter table public.odds_snapshots enable row level security;
alter table public.prediction_results enable row level security;
alter table public.source_sync_runs enable row level security;

do $$ begin
  create policy "public read countries" on public.countries for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "public read leagues" on public.leagues for select to anon, authenticated using (active = true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "public read teams" on public.teams for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "public read referees" on public.referees for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "public read fixtures" on public.fixtures for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "public read referee profiles" on public.referee_profiles for select to anon, authenticated using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "public read published predictions" on public.predictions for select to anon, authenticated using (publish_status = 'published');
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "public read published prediction results" on public.prediction_results for select to anon, authenticated using (
    exists (
      select 1 from public.predictions p
      where p.id = prediction_results.prediction_id
        and p.publish_status = 'published'
    )
  );
exception when duplicate_object then null; end $$;

revoke all on function public.refresh_referee_profiles() from public;
revoke all on function public.refresh_referee_profiles() from anon;
revoke all on function public.refresh_referee_profiles() from authenticated;
revoke all on function public.settle_v0_predictions() from public;
revoke all on function public.settle_v0_predictions() from anon;
revoke all on function public.settle_v0_predictions() from authenticated;

comment on table public.team_match_stats is 'Compact match statistics used to build card, corner and goal features. Keep raw provider payloads out of the database to protect the free-tier storage budget.';
comment on table public.feature_snapshots is 'Pre-match feature snapshots only. Features must use data available before kickoff to avoid look-ahead bias.';
comment on table public.predictions is 'Research-model outputs. Publish only selections that pass data-quality and model gates.';
comment on view public.team_match_flat is 'Service-side modelling view. One row per team per completed fixture with opponent context.';
comment on function public.refresh_referee_profiles() is 'Rebuilds rolling two-year referee card/foul profiles from stored completed matches.';
comment on function public.settle_v0_predictions() is 'Settles v0 card/corner/goal selections from completed fixture statistics. No price-based P/L is calculated until odds are recorded.';
comment on view public.scanner_performance is 'Public hit-rate summary for published EVE selections. ROI is intentionally excluded until taken odds are captured.';

select 'EVE Football Scanner database setup complete' as status;
