-- EVE Football Scanner — EXPANSION V1
-- ONE-SHOT SQL. Run this once in the dedicated FREE eve-football-scanner Supabase project.
-- Adds expanded markets, manual referee/starting-XI context, player history and same-game combo research.

create extension if not exists pgcrypto;

-- Broaden the market taxonomy while preserving the existing tables.
alter table public.feature_snapshots drop constraint if exists feature_snapshots_market_check;
alter table public.feature_snapshots
  add constraint feature_snapshots_market_check
  check (market in ('cards','corners','goals','btts','team_goals','half_goals','match_cards','match_corners','player','combo'));

alter table public.predictions drop constraint if exists predictions_market_check;
alter table public.predictions
  add constraint predictions_market_check
  check (market in ('cards','corners','goals','btts','team_goals','half_goals','match_cards','match_corners','player','combo'));

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'fotmob',
  source_player_id text,
  name text not null,
  current_team_id uuid references public.teams(id) on delete set null,
  position text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source, source_player_id)
);

create table if not exists public.player_match_stats (
  id bigint generated by default as identity primary key,
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  started boolean not null default false,
  minutes smallint,
  shots smallint,
  shots_on_target smallint,
  goals smallint,
  assists smallint,
  yellow_cards smallint,
  red_cards smallint,
  fouls_committed smallint,
  fouls_won smallint,
  xg numeric(7,3),
  xa numeric(7,3),
  source text not null default 'fotmob',
  created_at timestamptz not null default now(),
  unique(fixture_id, player_id)
);

create table if not exists public.fixture_lineups (
  id bigint generated by default as identity primary key,
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  is_starting boolean not null default true,
  shirt_number smallint,
  position text,
  source text not null default 'manual',
  confirmed_at timestamptz not null default now(),
  unique(fixture_id, player_id, source)
);

create table if not exists public.manual_match_context (
  fixture_id uuid primary key references public.fixtures(id) on delete cascade,
  referee_name text,
  referee_confirmed boolean not null default false,
  lineups_confirmed boolean not null default false,
  notes text,
  confirmed_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.combo_recommendations (
  id uuid primary key default gen_random_uuid(),
  fixture_id uuid not null references public.fixtures(id) on delete cascade,
  model_version text not null default 'v1-combo-research',
  sample_size smallint not null default 0,
  singles jsonb not null default '[]'::jsonb,
  doubles jsonb not null default '[]'::jsonb,
  treble jsonb,
  explanation text,
  data_quality smallint not null default 0 check (data_quality between 0 and 100),
  calculated_at timestamptz not null default now(),
  unique(fixture_id, model_version)
);

create index if not exists players_team_idx on public.players(current_team_id);
create index if not exists player_stats_player_fixture_idx on public.player_match_stats(player_id, fixture_id);
create index if not exists player_stats_team_fixture_idx on public.player_match_stats(team_id, fixture_id);
create index if not exists fixture_lineups_fixture_team_idx on public.fixture_lineups(fixture_id, team_id, is_starting);
create index if not exists combo_fixture_idx on public.combo_recommendations(fixture_id, calculated_at desc);

create or replace view public.fixture_match_flat
with (security_invoker = true)
as
select
  f.id as fixture_id,
  f.kickoff,
  f.league_id,
  f.home_team_id,
  f.away_team_id,
  f.home_goals,
  f.away_goals,
  f.half_time_home_goals,
  f.half_time_away_goals,
  coalesce(hs.yellow_cards,0) as home_yellow_cards,
  coalesce(aw.yellow_cards,0) as away_yellow_cards,
  coalesce(hs.yellow_cards,0) + coalesce(aw.yellow_cards,0) as total_yellow_cards,
  coalesce(hs.corners,0) as home_corners,
  coalesce(aw.corners,0) as away_corners,
  coalesce(hs.corners,0) + coalesce(aw.corners,0) as total_corners,
  coalesce(f.home_goals,0) + coalesce(f.away_goals,0) as total_goals,
  case when coalesce(f.home_goals,0) > 0 and coalesce(f.away_goals,0) > 0 then true else false end as btts,
  coalesce(f.half_time_home_goals,0) + coalesce(f.half_time_away_goals,0) as first_half_goals,
  (coalesce(f.home_goals,0) + coalesce(f.away_goals,0)) - (coalesce(f.half_time_home_goals,0) + coalesce(f.half_time_away_goals,0)) as second_half_goals
from public.fixtures f
join public.team_match_stats hs on hs.fixture_id = f.id and hs.team_id = f.home_team_id
join public.team_match_stats aw on aw.fixture_id = f.id and aw.team_id = f.away_team_id
where f.status = 'finished';

-- Existing Value Engine setup created this view with an older column layout.
-- Drop/recreate avoids PostgreSQL CREATE OR REPLACE column-order restrictions.
drop view if exists public.scanner_best_bets;

create view public.scanner_best_bets
with (security_invoker = true)
as
select
  p.id,
  f.id as "fixtureId",
  c.name as country,
  l.name as league,
  ht.name as "homeTeam",
  at.name as "awayTeam",
  to_char(f.kickoff at time zone 'Europe/London', 'HH24:MI') as kickoff,
  f.kickoff as "kickoffUtc",
  p.market,
  p.selection,
  p.confidence,
  p.grade,
  p.data_quality as "dataQuality",
  p.evidence,
  case when r.id is null then null else jsonb_build_object('name',r.name,'cardsPerMatch',rp.yellow_cards_per_match,'foulsPerMatch',rp.fouls_per_match) end as referee,
  case when p.fair_probability is null then null else round((p.fair_probability * 100)::numeric, 1) end as "fairProbability",
  case when p.fair_probability is null or p.fair_probability <= 0 then null else round((1 / p.fair_probability)::numeric, 2) end as "fairOdds",
  bo.bookmaker as "bestBookmaker",
  bo.decimal_odds as "bestOdds",
  bo.captured_at as "oddsCapturedAt",
  case when bo.decimal_odds is null then null else round((100 / bo.decimal_odds)::numeric, 1) end as "impliedProbability",
  case when bo.decimal_odds is null or p.fair_probability is null then null else round(((p.fair_probability - (1 / bo.decimal_odds)) * 100)::numeric, 1) end as "edgePct",
  case when bo.decimal_odds is null or p.fair_probability is null then null else round(((p.fair_probability * bo.decimal_odds - 1) * 100)::numeric, 1) end as "expectedValuePct",
  case
    when p.fair_probability is null then 'uncalibrated'
    when bo.decimal_odds is null then 'waiting'
    when (p.fair_probability - (1 / bo.decimal_odds)) >= 0.07 and (p.fair_probability * bo.decimal_odds - 1) >= 0.10 then 'strong'
    when (p.fair_probability - (1 / bo.decimal_odds)) >= 0.05 and (p.fair_probability * bo.decimal_odds - 1) >= 0.05 then 'value'
    else 'no_value'
  end as "valueStatus"
from public.predictions p
join public.fixtures f on f.id = p.fixture_id
join public.leagues l on l.id = f.league_id
join public.countries c on c.id = l.country_id
join public.teams ht on ht.id = f.home_team_id
join public.teams at on at.id = f.away_team_id
left join public.referees r on r.id = f.referee_id
left join lateral (
  select yellow_cards_per_match, fouls_per_match
  from public.referee_profiles rp0
  where rp0.referee_id = r.id
  order by rp0.as_of_date desc
  limit 1
) rp on true
left join lateral (
  select os.bookmaker, os.decimal_odds, os.captured_at
  from public.odds_snapshots os
  where os.prediction_id = p.id and os.captured_at >= now() - interval '8 hours'
  order by os.decimal_odds desc, os.captured_at desc
  limit 1
) bo on true
where p.publish_status = 'published'
  and p.model_version = 'v0-research'
  and f.status in ('scheduled','live')
  and f.kickoff >= now() - interval '3 hours'
order by p.confidence desc;

create or replace view public.scanner_expanded_markets
with (security_invoker = true)
as
select
  p.id,
  f.id as "fixtureId",
  c.name as country,
  l.name as league,
  ht.name as "homeTeam",
  at.name as "awayTeam",
  to_char(f.kickoff at time zone 'Europe/London', 'HH24:MI') as kickoff,
  f.kickoff as "kickoffUtc",
  p.market,
  p.selection,
  p.confidence,
  p.grade,
  p.data_quality as "dataQuality",
  p.evidence,
  fs.selection_key as "selectionKey",
  fs.features,
  case when r.id is null then null else jsonb_build_object('name',r.name,'cardsPerMatch',rp.yellow_cards_per_match,'matchesSample',rp.matches_sample) end as referee,
  coalesce(mmc.lineups_confirmed,false) as "lineupsConfirmed",
  coalesce(mmc.referee_confirmed,false) as "refereeConfirmed"
from public.predictions p
join public.feature_snapshots fs on fs.id = p.feature_snapshot_id
join public.fixtures f on f.id = p.fixture_id
join public.leagues l on l.id = f.league_id
join public.countries c on c.id = l.country_id
join public.teams ht on ht.id = f.home_team_id
join public.teams at on at.id = f.away_team_id
left join public.manual_match_context mmc on mmc.fixture_id = f.id
left join public.referees r on r.id = f.referee_id
left join lateral (
  select yellow_cards_per_match, matches_sample
  from public.referee_profiles rp0
  where rp0.referee_id = r.id
  order by rp0.as_of_date desc
  limit 1
) rp on true
where p.model_version = 'v1-expanded-research'
  and p.publish_status = 'published'
  and f.status in ('scheduled','live')
  and f.kickoff >= now() - interval '3 hours'
order by p.confidence desc;

create or replace view public.fixture_setup_board
with (security_invoker = true)
as
select
  f.id as "fixtureId",
  c.name as country,
  l.name as league,
  ht.id as "homeTeamId",
  ht.name as "homeTeam",
  at.id as "awayTeamId",
  at.name as "awayTeam",
  f.kickoff,
  r.name as referee,
  coalesce(mmc.referee_confirmed,false) as "refereeConfirmed",
  coalesce(mmc.lineups_confirmed,false) as "lineupsConfirmed",
  count(fl.id) filter (where fl.team_id = f.home_team_id and fl.is_starting) as "homeStarters",
  count(fl.id) filter (where fl.team_id = f.away_team_id and fl.is_starting) as "awayStarters"
from public.fixtures f
join public.leagues l on l.id = f.league_id
join public.countries c on c.id = l.country_id
join public.teams ht on ht.id = f.home_team_id
join public.teams at on at.id = f.away_team_id
left join public.referees r on r.id = f.referee_id
left join public.manual_match_context mmc on mmc.fixture_id = f.id
left join public.fixture_lineups fl on fl.fixture_id = f.id
where f.status in ('scheduled','live')
  and f.kickoff >= now() - interval '3 hours'
  and f.kickoff < now() + interval '8 days'
group by f.id,c.name,l.name,ht.id,ht.name,at.id,at.name,f.kickoff,r.name,mmc.referee_confirmed,mmc.lineups_confirmed
order by f.kickoff;

create or replace view public.fixture_player_outlook
with (security_invoker = true)
as
select
  fl.fixture_id as "fixtureId",
  fl.team_id as "teamId",
  t.name as "teamName",
  p.id as "playerId",
  p.name,
  coalesce(fl.position,p.position) as position,
  fl.is_starting as "isStarting",
  form.matches as "matchesSample",
  form.avg_minutes as "avgMinutes",
  form.avg_shots as "avgShots",
  form.avg_sot as "avgShotsOnTarget",
  form.avg_goals as "avgGoals",
  form.avg_cards as "avgYellowCards"
from public.fixture_lineups fl
join public.fixtures current_fixture on current_fixture.id = fl.fixture_id
join public.players p on p.id = fl.player_id
join public.teams t on t.id = fl.team_id
left join lateral (
  select
    count(*)::integer as matches,
    round(avg(x.minutes)::numeric,1) as avg_minutes,
    round(avg(x.shots)::numeric,2) as avg_shots,
    round(avg(x.shots_on_target)::numeric,2) as avg_sot,
    round(avg(x.goals)::numeric,2) as avg_goals,
    round(avg(x.yellow_cards)::numeric,2) as avg_cards
  from (
    select pms.*
    from public.player_match_stats pms
    join public.fixtures pf on pf.id = pms.fixture_id
    where pms.player_id = p.id and pf.kickoff < current_fixture.kickoff and pf.status = 'finished'
    order by pf.kickoff desc
    limit 10
  ) x
) form on true
where fl.is_starting = true;

create or replace view public.combo_board
with (security_invoker = true)
as
select
  cr.id,
  cr.fixture_id as "fixtureId",
  c.name as country,
  l.name as league,
  ht.name as "homeTeam",
  at.name as "awayTeam",
  f.kickoff,
  cr.sample_size as "sampleSize",
  cr.singles,
  cr.doubles,
  cr.treble,
  cr.explanation,
  cr.data_quality as "dataQuality",
  cr.calculated_at as "calculatedAt"
from public.combo_recommendations cr
join public.fixtures f on f.id = cr.fixture_id
join public.leagues l on l.id = f.league_id
join public.countries c on c.id = l.country_id
join public.teams ht on ht.id = f.home_team_id
join public.teams at on at.id = f.away_team_id
where f.status in ('scheduled','live') and f.kickoff >= now() - interval '3 hours'
order by f.kickoff, cr.data_quality desc;

create or replace function public.settle_expanded_predictions()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare affected integer := 0;
begin
  insert into public.prediction_results (prediction_id, outcome, settled_at)
  select p.id,
    case
      when fs.selection_key = 'btts_yes' then case when coalesce(f.home_goals,0) > 0 and coalesce(f.away_goals,0) > 0 then 'win' else 'loss' end
      when fs.selection_key = 'home_goals_0_5' then case when coalesce(f.home_goals,0) >= 1 then 'win' else 'loss' end
      when fs.selection_key = 'away_goals_0_5' then case when coalesce(f.away_goals,0) >= 1 then 'win' else 'loss' end
      when fs.selection_key = 'home_goals_1_5' then case when coalesce(f.home_goals,0) >= 2 then 'win' else 'loss' end
      when fs.selection_key = 'away_goals_1_5' then case when coalesce(f.away_goals,0) >= 2 then 'win' else 'loss' end
      when fs.selection_key = 'first_half_0_5' then case when coalesce(f.half_time_home_goals,0) + coalesce(f.half_time_away_goals,0) >= 1 then 'win' else 'loss' end
      when fs.selection_key = 'match_cards_3_5' then case when coalesce(hs.yellow_cards,0) + coalesce(aw.yellow_cards,0) >= 4 then 'win' else 'loss' end
      when fs.selection_key = 'match_corners_8_5' then case when coalesce(hs.corners,0) + coalesce(aw.corners,0) >= 9 then 'win' else 'loss' end
      else 'void'
    end,
    now()
  from public.predictions p
  join public.feature_snapshots fs on fs.id = p.feature_snapshot_id
  join public.fixtures f on f.id = p.fixture_id and f.status = 'finished'
  left join public.team_match_stats hs on hs.fixture_id = f.id and hs.team_id = f.home_team_id
  left join public.team_match_stats aw on aw.fixture_id = f.id and aw.team_id = f.away_team_id
  left join public.prediction_results existing on existing.prediction_id = p.id
  where existing.prediction_id is null and p.model_version = 'v1-expanded-research';
  get diagnostics affected = row_count;
  return affected;
end;
$$;

alter table public.players enable row level security;
alter table public.player_match_stats enable row level security;
alter table public.fixture_lineups enable row level security;
alter table public.manual_match_context enable row level security;
alter table public.combo_recommendations enable row level security;

do $$ begin create policy "public read players" on public.players for select to anon, authenticated using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public read player stats" on public.player_match_stats for select to anon, authenticated using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public read fixture lineups" on public.fixture_lineups for select to anon, authenticated using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public read manual context" on public.manual_match_context for select to anon, authenticated using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public read combos" on public.combo_recommendations for select to anon, authenticated using (true); exception when duplicate_object then null; end $$;

grant select on public.fixture_match_flat to anon, authenticated;
grant select on public.scanner_best_bets to anon, authenticated;
grant select on public.scanner_expanded_markets to anon, authenticated;
grant select on public.fixture_setup_board to anon, authenticated;
grant select on public.fixture_player_outlook to anon, authenticated;
grant select on public.combo_board to anon, authenticated;

revoke all on function public.settle_expanded_predictions() from public;
revoke all on function public.settle_expanded_predictions() from anon;
revoke all on function public.settle_expanded_predictions() from authenticated;

comment on table public.player_match_stats is 'Compact rolling player match history for starting-XI analysis. Player markets remain research until independently calibrated.';
comment on table public.manual_match_context is 'Manual match-day confirmation of referee and starting lineups. Confirmation triggers re-analysis through Netlify.';
comment on table public.combo_recommendations is 'Same-game combination research. Double/treble probabilities are empirical joint frequencies from historical comparable matches, not multiplied single-leg percentages.';
comment on view public.scanner_expanded_markets is 'Expanded research markets: BTTS, team goals, half goals, match cards and match corners. Kept separate from calibrated Best Bets until backtested.';

select 'EVE Expansion V1 database setup complete' as status;
